name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: RodarTestes
      id: rodartestes
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: RodarTestes
        setup-command: dotnet test
        command: dotnet test --project ./TestesFixacaoConceitosBasicos1/TestesFixacaoConceitosBasicos1.csproj
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RODARTESTES_RESULTS: "${{steps.rodartestes.outputs.result}}"
      with:
        runners: rodartestes
